description: Handcrafted train server params
experiments:
- chunk_size: 1024
  name: benchmark-1
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 1024
    max_model_len: 8192
    max_num_batched_tokens: 4096
    max_num_seqs: 1
    seed: 42
- chunk_size: 2048
  name: benchmark-2
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 2048
    max_model_len: 8192
    max_num_batched_tokens: 4096
    max_num_seqs: 1
    seed: 42
- chunk_size: 4096
  name: benchmark-3
  vllm:
    block_size: 16
    gpu_memory_min: 50000
    gpu_memory_utilization: 0.9
    gpu_type: NVIDIA-H100-80GB-HBM3
    long_prefill_token_threshold: 4096
    max_model_len: 8192
    max_num_batched_tokens: 4096
    max_num_seqs: 1
    seed: 42
name: train_server_config_for_scenario_3